---
- name: Install filebeat
  hosts: nginx
  become: yes

  tasks:
    - name: Install gnupg, apt-transport-https
      apt:
        name:
          - apt-transport-https
          - gnupg
        state: present

    - name: Get filebeat 7.17.14
      ansible.builtin.get_url:
        url: https://mirror.yandex.ru/mirrors/elastic/7/pool/main/f/filebeat/filebeat-7.17.14-amd64.deb
        dest: /home/morzin/

    - name: Install filebeat
      apt:
        deb: /home/morzin/filebeat-7.17.14-amd64.deb 

    - name: Copy config file for filebeat
      copy:
        src: /home/morzin/diplom/ansible/config/filebeat.yml
        dest: /etc/filebeat
        mode: 0644
        owner: root
        group: root
 
    - name: enable and restart filebeat
      ansible.builtin.systemd:
        name: filebeat
        enabled: yes
        masked: no
        state: restarted